#ifndef _PARSER_COMMON_H__INCLUDED_
#define _PARSER_COMMON_H__INCLUDED_



// see the comment in parser.y, next to the 'file' rule.  I think this is a
// hack, but it's the best I have so far.

#include "wiring/core.h"

extern HWC_Wiring *bisonParseRoot;



// declared and maintained by the lexer
extern int colNum;

// this is also declared and maintained by the lexer - but it is code that
// is auto-generated by flex.
extern int yylineno;



// implemented by the code in the parser, called by the lexer.
int tokenLookup(char *str);



#endif

