#include <stdio.h>
#include <malloc.h>
#include <memory.h>

#include <assert.h>

#include "phase10.h"

// fileScope the name scope for the entire file
HWC_Part *semPhase10_part(PT_part_decl *parsedPart, HWC_NameScope *fileScope)
{
	HWC_Part *retval = malloc(sizeof(HWC_Part));
	if (retval == NULL)
	{
		assert(0);   // TODO: debug message
		return NULL;
	}
	memset(retval, 0, sizeof(*retval));


	retval->phases_completed = retval->phases_begun = 10;

	// Create publicNames, and make "fileScope" its parent
	retval->publicNames = nameScope_malloc(fileScope);
	if (retval->publicNames == NULL)
	{
		assert(0);   // TODO: debug message
		free(retval);
		return NULL;
	}

	HWC_Decl *decl_list_head;
	int decl_list_size;
	// Implementation can be found in stmts.c
	// Creates an ordered (? Not necessary) list of decls within this part.
	decl_list_size = extractHWCdeclsFromPTstmts(parsedPart->stmts, decl_list_head);

	// Implementation can be found in stmts.c
	// Converts the list of pt_stmts generated by the gramamr into HWC_Stmts
	retval->stmts_len = convertPTstmtIntoHWCstmt(parsedPart->stmts, retval->stmts, retval);

	return retval;
}

