#ifndef _PARSER_COMMON_H__INCLUDED_
#define _PARSER_COMMON_H__INCLUDED_



// see the comment in parser.y, next to the 'file' rule.  I think this is a
// hack, but it's the best I have so far.

#include "pt/file.h"
extern PT_file *bisonParseRoot;



// declared and maintained by the lexer
extern int colNum;

// this is also declared and maintained by the lexer - but it is code that
// is auto-generated by flex.
extern int yylineno;



// declared and initialized by main(), so that we can fill in the FileRange
// structs.
extern char *bisonParse_filename;



// implemented by the code in the parser, called by the lexer.
int tokenLookup(char *str, int assertFound);



#endif

